<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends \Spatie\Permission\Models\Role
{
    use SoftDeletes;

    // public function users() : MorphToMany
    // {
    //     $project = Project::curProject();
    //     return parent::users()->wherePivot('project', $project['code']); // TODO: Change the autogenerated stub
    // }
}